name = "carp"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "Carp"
database_name = "carpp"
database_id = "fdf58de9-0999-4b65-974f-392b2a845537"

[vars]
SUPER_ADMIN_USERNAME = "test"
SUPER_ADMIN_PASSWORD = "test@2026"
DEFAULT_ADMIN_PASSWORD = "test@123456"
DEFAULT_USE_COUNT = "5"
JWT_SECRET = "carp-hotel-parking-jwt-secret-2026"

