name = "hcar"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "Carp"
database_name = "hcar"
database_id = "043e757f-8806-4671-be37-39b73429e1e4"

[vars]
SUPER_ADMIN_USERNAME = "test"
SUPER_ADMIN_PASSWORD = "test@2026"
DEFAULT_ADMIN_PASSWORD = "test@123456"
DEFAULT_USE_COUNT = "5"
JWT_SECRET = "hcarp-hotel-parking-jwt-secret-2026"

