name = "carp"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "carp"
database_name = "carp"
database_id = "34f26871-de77-4d7d-92dc-a2cad3738ad3"

[vars]
SUPER_ADMIN_USERNAME = "test"
SUPER_ADMIN_PASSWORD = "test@2026"
DEFAULT_ADMIN_PASSWORD = "test@123456"
DEFAULT_USE_COUNT = "5"
JWT_SECRET = "hcarp-hotel-parking-jwt-secret-2026"

